### ISSUE TITLE
Subir EDT

### ISSUE THREAD

**Issue by stroomed** [stroomed/tesis2020#12]
### Fabricio
- [x] Diseñar EDT.
- [x] Entregar diccionario del EDT.

### Ricardo
- [x] Revisar EDT entregado por Fabricio.
- [x] Revisar diccionario EDT entregado por Fabricio.

---

El EDT, su diccionario y las correspondientes revisiones deberán ser subidas al issue como comentario (no editar issue).

---

- [x] Revisión hecha por Nicol Quintuy
- [x] Revisión hecha por Gabriel Barría

**Comment by Aijin-01** [comment]
![EDT](https://user-images.githubusercontent.com/62028929/80931391-89c96500-8d87-11ea-824a-119b4cbee94b.png)

**Comment by Gabriel-Barria** [comment]
Faltarían los entregables en cada fase, en la fase de diseño es en la única parte donde se ve un claro entregable que sería el diseño de la base de datos. Estiria bueno agregar documentación como parte de las actividades en la fase de desarrollo y su entregable vendría siendo la mismo api. Es buena práctica documentar el código

**Comment by stroomed** [comment]
Coincido con Gabriel, creo que la versión corregida que has subido es bastante más completa. Sin embargo, creo que en la parte de planificación podría ir agregado el plan de compras y contrataciones. Fuera de eso, todo ok.

**Comment by Aijin-01** [comment]
Código | 1.       Fase de análisis
-- | --
Descripción | Se realizan el   análisis del proyecto en diferentes ámbitos, preparando el desarrollo.
Responsable | Director de proyecto
Recursos | Ricardo Gutiérrez,   Gabriel Barría, Nicol Quintuy, Fabricio Guzmán
Duración | 15 días
Resultados | Análisis y   planificación completa del proyecto
Restricciones | No aplica
Dependencias | No aplica
Criterios de aceptación | Revisión del equipo   y cliente


Código | 1.1 Especificación   del problema
-- | --
Descripción | Investigación sobre   la problemática encontrada.
Responsable | Director de proyecto
Recursos | Ricardo Gutiérrez,   Gabriel Barría, Nicol Quintuy, Fabricio Guzmán.
Duración | 6 días
Resultados | Oportunidad de   negocio en base a una problemática
Restricciones | No aplica
Dependencias | 1.0
Criterios de aceptación | Aceptación del   equipo y cliente


Código | 1.1.1 Objetivo   General
-- | --
Descripción | Se describe el   objetivo general sobre el proyecto.
Responsable | Ricardo Gutiérrez
Recursos | Ricardo Gutiérrez
Duración | 3 día
Resultados | Descripción sobre lo   que llegará a ser el proyecto
Restricciones | No aplica
Dependencias | 1.1
Criterios de aceptación | Aceptación del   equipo


Código | 1.1.2 Objetivos   específicos
-- | --
Descripción | Se describe los   objetivos específicos sobre el proyecto
Responsable | Ricardo Gutiérrez
Recursos | Ricardo Gutiérrez
Duración | 3 día
Resultados | Descripción de los   pasos para lograr el objetivo general
Restricciones | No aplica
Dependencias | 1.1
Criterios de aceptación | Aceptación del   equipo


Código | 1.2 Toma de   requerimientos
-- | --
Descripción | Se toman las   necesidades del cliente para el proyecto
Responsable | Director de proyecto
Recursos | Fabricio Guzmán
Duración | 2 día
Resultados | Ideas iniciales   sobre lo que será la solución
Restricciones | No aplica
Dependencias | 1.0
Criterios de aceptación | Aceptación del   equipo y cliente


Código | 1.2.1 Identificación   de requerimientos funcionales
-- | --
Descripción | Después de tomar los   requerimientos, estos son diferenciados.
Responsable | Fabricio Guzmán
Recursos | Fabricio Guzmán
Duración | 1 día
Resultados | Distinción de los   requerimientos funcionales de los no funcionales
Restricciones | No aplica
Dependencias | 1.2
Criterios de aceptación | Aceptación del   equipo y cliente


Código | 1.2.2 Identificación   de requerimientos no funcionales
-- | --
Descripción | Después de tomar los   requerimientos, estos son diferenciados.
Responsable | Fabricio Guzmán
Recursos | Fabricio Guzmán
Duración | 1 día
Resultados | Distinción de los   requerimientos no funcionales de los funcionales
Restricciones | No aplica
Dependencias | 1.2
Criterios de aceptación | Aceptación del   equipo y cliente


Código | 1.3 Planificación
-- | --
Descripción | Se planifica todo lo   necesario para comenzar con el proyecto.
Responsable | Director de proyecto
Recursos | Ricardo Gutiérrez,   Gabriel Barría, Nicol Quintuy, Fabricio Guzmán.
Duración | 7 días
Resultados | Distinción de los   requerimientos no funcionales de los funcionales
Restricciones | No aplica
Dependencias | 1.2
Criterios de aceptación | Aceptación del   equipo y cliente



Código | 1.3.1 Definición de   alcance
-- | --
Descripción | Se define el alcance   del proyecto
Responsable | Ricardo Gutiérrez
Recursos | Ricardo Gutiérrez
Duración | 1 día
Resultados | Alcance del proyecto
Restricciones | No aplica
Dependencias | 1.3
Criterios de aceptación | Aceptación del   equipo


Código | 1.3.2 Plan de   calidad
-- | --
Descripción | Se define el plan y   estándares de calidad para el proyecto
Responsable | Gabriel Barría
Recursos | Gabriel Barría
Duración | 2 días
Resultados | Proceso de   aseguramiento de calidad del proyecto
Restricciones | No aplica
Dependencias | 1.3


Código | 1.3.3 Definición de   costes
-- | --
Descripción | Se define los costos   para el proyecto
Responsable | Nicol Quintuy,   Gabriel Barría
Recursos | Nicol Quintuy,   Gabriel Barría
Duración | 2 días
Resultados | Presupuesto para el   proyecto, plan de compras y las contrataciones a realizar.
Restricciones | No aplica
Dependencias | 1.3
Criterios de aceptación | Aceptación del   equipo


Código | 1.3.4 Plan de   riesgos
-- | --
Descripción | Se define los   riesgos del proyecto y el plan a tomar en contra
Responsable | Nicol Quintuy
Recursos | Nicol Quintuy
Duración | 2 días
Resultados | Identificación de   probabilidad e impacto de los riegos, elaborar las estrategias de defensa y   plan de respuesta de los riesgos.
Restricciones | No aplica
Dependencias | 1.3
Criterios de aceptación | Aceptación del   equipo


Código | 2.0 Fase de Diseño
-- | --
Descripción | Se realizan diseños previos al desarrollo
Responsable | Director de proyecto
Recursos | Ricardo Gutiérrez,   Gabriel Barría, Nicol Quintuy, Fabricio Guzmán
Duración | 17 días
Resultados | Template analizado,   Diagramas UML, Diseño de bases de datos
Restricciones | No aplica
Dependencias | No aplica
Criterios de aceptación | Aceptación del   equipo y Cliente


Código | 2.1 Adaptación del   template
-- | --
Descripción | Se realiza el   análisis del template
Responsable | Director de proyecto
Recursos | Gabriel Barría, Fabricio   Guzmán
Duración | 7 días
Resultados | Integración completa   del template al proyecto
Restricciones | Basado en https://github.com/ColorlibHQ/AdminLTE
Dependencias | 2.0
Criterios de aceptación | Aceptación del   equipo


Código | 2.1.1 Template de   Admin
-- | --
Descripción | Se integra el   template al proyecto.
Responsable | Gabriel Barría,   Fabricio Guzmán
Recursos | Gabriel Barría,   Fabricio Guzmán
Duración | 7 días
Resultados | Integración del   template al proyecto
Restricciones | Basado en https://github.com/ColorlibHQ/AdminLTE
Dependencias | 2.1
Criterios de aceptación | Aceptación del   equipo


Código | 2.2 Diagramas UML
-- | --
Descripción | Se crean diversos   diagramas en base al proyecto
Responsable | Director de proyecto
Recursos | Ricardo Gutiérrez, Fabricio   Guzmán
Duración | 4 días
Resultados | Diagramas de casos   de usos y diagramas de clases.
Restricciones | No aplica
Dependencias | 2.0
Criterios de aceptación | Aceptación del   equipo


Código | 2.2.1 Casos de uso
-- | --
Descripción | Se crean los casos   de uso del proyecto.
Responsable | Fabricio Guzmán
Recursos | Fabricio Guzmán
Duración | 2 días
Resultados | Diagramas de casos   de usos y su documentación.
Restricciones | No aplica
Dependencias | 2.2
Criterios de aceptación | Aceptación del   equipo


Código | 2.2.2 Diagramas de   clase
-- | --
Descripción | Se crean los   diagramas de clases del proyecto.
Responsable | Ricardo Gutiérrez
Recursos | Ricardo Gutiérrez
Duración | 2 días
Resultados | Entrega de diagramas   clases
Restricciones | No aplica
Dependencias | 2.2
Criterios de aceptación | Aceptación del   equipo


Código | 2.3 Diseño de base   de datos
-- | --
Descripción | Se crean las bases   de datos para el proyecto.
Responsable | Director de proyecto
Recursos | Gabriel Barría,   Nicol Quintuy
Duración | 6 días
Resultados | Entrega de Bases de   datos
Restricciones | Base de datos de   información en MongoDB
Dependencias | 2.0
Criterios de aceptación | Aceptación del   equipo


Código | 2.3.1 Diseño de base   de datos no relacional
-- | --
Descripción | Se crea la base de   datos para el proyecto.
Responsable | Gabriel Barría,   Nicol Quintuy
Recursos | Gabriel Barría,   Nicol Quintuy
Duración | 3 días
Resultados | Entrega de Bases de   datos para la información
Restricciones | Base de datos de   información en MongoDB
Dependencias | 2.3
Criterios de aceptación | Aceptación del   equipo


Código | 2.3.2 Diseño de base   de datos de los usuarios
-- | --
Descripción | Se crea la base de   datos para los usuarios.
Responsable | Gabriel Barría,   Nicol Quintuy
Recursos | Gabriel Barría,   Nicol Quintuy
Duración | 3 días
Resultados | Entrega de Bases de   datos para los usuarios
Restricciones | No aplica
Dependencias | 2.3
Criterios de aceptación | Aceptación del   equipo


Código | 3.0 Fase de   desarrollo
-- | --
Descripción | Fase de desarrollo   de la API.
Responsable | Director de proyecto
Recursos | Ricardo Gutiérrez,   Gabriel Barría, Nicol Quintuy, Fabricio Guzmán.
Duración | 30 días
Resultados | Desarrollo de la API   completa
Restricciones | No aplica
Dependencias | No aplica
Criterios de aceptación | Aceptación del   equipo


Código | 3.1 Creación de base   de datos
-- | --
Descripción | Se crean la bases de   datos necesarias.
Responsable | Director de proyecto
Recursos | Ricardo Gutiérrez,   Gabriel Barría
Duración | 7 días
Resultados | Creación de base de   datos.
Restricciones | Bases de datos   separadas entre MongoDB y la de usuarios
Dependencias | 3.0
Criterios de aceptación | Aceptación del   equipo


Código | 3.1.1 Base de datos   en MongoDB
-- | --
Descripción | Se crea la base de   datos para la información.
Responsable | Ricardo Gutiérrez,   Gabriel Barría
Recursos | Ricardo Gutiérrez,   Gabriel Barría
Duración | 4 días
Resultados | Base de datos para   la información de las solicitudes.
Restricciones | Base de datos creada   en MongoDB
Dependencias | 3.1
Criterios de aceptación | Aceptación del   equipo


Código | 3.1.2 Base de datos   para usuarios
-- | --
Descripción | Se crea la base de   datos para los usuarios.
Responsable | Ricardo Gutiérrez,   Gabriel Barría
Recursos | Ricardo Gutiérrez,   Gabriel Barría
Duración | 3 días
Resultados | Base de datos para   la información de los usuarios y sus privilegios.
Restricciones | No aplica
Dependencias | 3.0
Criterios de aceptación | Aceptación del   equipo


Código | 3.2 Desarrollo de la   API
-- | --
Descripción | Se da inicio al   desarrollo de la API.
Responsable | Director de proyecto
Recursos | Gabriel Barría,   Nicol Quintuy, Fabricio Guzmán.
Duración | 23 días
Resultados | Aplicación   terminada.
Restricciones | No aplica
Dependencias | 3.0
Criterios de aceptación | Aceptación del   equipo


Código | 3.2.1 Desarrollo en   Django Rest
-- | --
Descripción | Se da inicio al   desarrollo de la API.
Responsable | Gabriel Barría,   Nicol Quintuy, Fabricio Guzmán.
Recursos | Gabriel Barría,   Nicol Quintuy, Fabricio Guzmán.
Duración | 18 días
Resultados | Aplicación   desarrollada con el framework Django Rest.
Restricciones | No aplica
Dependencias | 3.2
Criterios de aceptación | Aceptación del   equipo


Código | 3.2.2 Documentación   de código
-- | --
Descripción | Se comenta el código   para documentarlo.
Responsable | Ricardo Gutiérrez,   Gabriel Barría, Nicol Quintuy, Fabricio Guzmán.
Recursos | Ricardo Gutiérrez,   Gabriel Barría, Nicol Quintuy, Fabricio Guzmán.
Duración | 5 días
Resultados | Aplicación   desarrollada con el framework Django Rest.
Restricciones | No aplica
Dependencias | 3.2
Criterios de aceptación | Aceptación del   equipo


Código | 4.0 Fase de pruebas
-- | --
Descripción | Se realizan diversas   pruebas al API y corrección de errores.
Responsable | Director de proyecto
Recursos | Ricardo Gutiérrez,   Gabriel Barría, Nicol Quintuy, Fabricio Guzmán.
Duración | 14 días
Resultados | Pruebas realizadas y   errores corregidos de la API.
Restricciones | No aplica
Dependencias | No aplica
Criterios de aceptación | Aceptación del   equipo


Código | 4.1 Pruebas   generales
-- | --
Descripción | Se realizan diversas   pruebas al API.
Responsable | Director de proyecto
Recursos | Ricardo Gutiérrez,   Gabriel Barría, Nicol Quintuy, Fabricio Guzmán.
Duración | 7 días
Resultados | Pruebas realizadas   en los diferente ámbitos de la API.
Restricciones | No aplica
Dependencias | 4.0
Criterios de aceptación | Aceptación del   equipo


Código | 4.1.1 Pruebas de   diseño
-- | --
Descripción | Se realizan pruebas   del diseño de interfaz.
Responsable | Ricardo Gutiérrez,   Gabriel Barría
Recursos | Ricardo Gutiérrez,   Gabriel Barría
Duración | 1 días
Resultados | Pruebas realizadas   las diferentes interfaces de la API.
Restricciones | No aplica
Dependencias | 4.1
Criterios de aceptación | Aceptación del   equipo


Código | 4.1.2 Pruebas de   estrés
-- | --
Descripción | Se realizan pruebas   de cantidad de conexiones activas y rendimiento.
Responsable | Ricardo Gutiérrez,   Gabriel Barría
Recursos | Ricardo Gutiérrez,   Gabriel Barría
Duración | 1 días
Resultados | Pruebas de   rendimiento y estrés realizadas a la API.
Restricciones | No aplica
Dependencias | 4.1
Criterios de aceptación | Aceptación del   equipo


Código | 4.1.3 Pruebas de   caja blanca
-- | --
Descripción | Se realizan pruebas   del código fuente.
Responsable | Fabricio Guzmán,   Nicol Quintuy
Recursos | Fabricio Guzmán,   Nicol Quintuy
Duración | 3 días
Resultados | Pruebas del   funcionamiento del código fuente.
Restricciones | No aplica
Dependencias | 4.1
Criterios de aceptación | Aceptación del   equipo


Código | 4.1.4 Pruebas de   caja negra
-- | --
Descripción | Se realizan pruebas   de la entrada y salida de información.
Responsable | Fabricio Guzmán,   Nicol Quintuy
Recursos | Fabricio Guzmán,   Nicol Quintuy
Duración | 2 días
Resultados | Pruebas de la   entrega de información resultante según solicitudes.
Restricciones | No aplica
Dependencias | 4.1
Criterios de aceptación | Aceptación del   equipo


Código | 4.2 Ajustes de   errores
-- | --
Descripción | Se realizan ajustes   y corrección de errores en la API.
Responsable | Director de proyecto
Recursos | Ricardo Gutiérrez,   Gabriel Barría, Nicol Quintuy, Fabricio Guzmán.
Duración | 7 días
Resultados | Errores y problemas   encontrados corregidos.
Restricciones | No aplica
Dependencias | 4.0
Criterios de aceptación | Aceptación del   equipo


Código | 4.2.1 API Corregida
-- | --
Descripción | Se terminan los   detalles y errores que se hayan encontrado.
Responsable | Ricardo Gutiérrez,   Gabriel Barría, Nicol Quintuy, Fabricio Guzmán.
Recursos | Ricardo Gutiérrez,   Gabriel Barría, Nicol Quintuy, Fabricio Guzmán.
Duración | 7 días
Resultados | Errores y problemas   encontrados corregidos, dando por terminado el desarrollo de la API.
Restricciones | No aplica
Dependencias | 4.2
Criterios de aceptación | Aceptación del   equipo


Código | 5.0 Fase de entrega
-- | --
Descripción | Se entrega r   implementa la API y su manual correspondiente.
Responsable | Director de proyecto
Recursos | Ricardo Gutiérrez,   Gabriel Barría, Nicol Quintuy, Fabricio Guzmán.
Duración | 7 días
Resultados | API implementada y   manual completado.
Restricciones | No aplica
Dependencias | No aplica
Criterios de aceptación | Aceptación del   equipo


Código | 5.1 Entrega de API
-- | --
Descripción | Se realiza la   entrega de la API.
Responsable | Director de proyecto
Recursos | Ricardo Gutiérrez,   Gabriel Barría, Nicol Quintuy, Fabricio Guzmán.
Duración | 4 días
Resultados | API entregada e   implementada.
Restricciones | No aplica
Dependencias | 5.0
Criterios de aceptación | Aceptación del   equipo y cliente


Código | 5.1.1 Implementación   de API
-- | --
Descripción | Se realiza la   implementación de la API.
Responsable | Ricardo Gutiérrez,   Gabriel Barría, Nicol Quintuy, Fabricio Guzmán.
Recursos | Ricardo Gutiérrez,   Gabriel Barría, Nicol Quintuy, Fabricio Guzmán.
Duración | 5 días
Resultados | API implementada.
Restricciones | No aplica
Dependencias | 5.1
Criterios de aceptación | Aceptación del   equipo y cliente


Código | 5.2 Manual de   usuario
-- | --
Descripción | Se realiza la   entrega del manual de usuario.
Responsable | Director de proyecto
Recursos | Ricardo Gutiérrez,   Gabriel Barría, Nicol Quintuy, Fabricio Guzmán.
Duración | 2 días
Resultados | Manual entregado
Restricciones | No aplica
Dependencias | 5.0
Criterios de aceptación | Aceptación del   equipo y cliente


Código | 5.2.1 Entrega de   manual de usuario
-- | --
Descripción | Se realiza la   creación y entrega del manual de usuario.
Responsable | Ricardo Gutiérrez,   Gabriel Barría, Nicol Quintuy, Fabricio Guzmán.
Recursos | Ricardo Gutiérrez,   Gabriel Barría, Nicol Quintuy, Fabricio Guzmán.
Duración | 2 días
Resultados | Manual Creado y   entregado.
Restricciones | No aplica
Dependencias | 5.2
Criterios de aceptación | Aceptación del   equipo y cliente

**Comment by stroomed** [comment]
Tengo mis dudas en el 1.2, donde se menciona que el responsable es el Director del proyecto, pero en los recursos solo está Fabricio, ¿no sería mejor dejar como responsable a Fabricio?
