### ISSUE TITLE
Subir cronograma

### ISSUE THREAD

**Issue by stroomed** [stroomed/tesis2020#13]
- [x] Diseñar cronograma (carta Gantt) en base a EDT.
- [x] Planificación de tiempos en base a tiempo de asignatura.

---

El cronograma y sus correspondientes revisiones deberán ser subidas al issue como comentario (no editar issue).

---

- [x] Revisión hecha por Gabriel Barría
- [x] Revisión hecha por Nicol Quintuy

**Comment by stroomed** [comment]
Entro carta Gantt vía whatsapp ya que GitHub no soporta el tipo de archivo

**Comment by Aijin-01** [comment]
en general esta bien, pero hay detalles notorios en el tema de tiempo y organización dentro de la gantt, por ejemplo, todas las tareas están determinadas como principales, no hay sub-tareas, guíate por los ID de las tareas, eso se puede hacer con los siguentes iconos dentro de Project: 
![image](https://user-images.githubusercontent.com/62028929/80922538-d4c58700-8d4b-11ea-9f4d-53bfd2f75f58.png)
ahí te darás cuenta de la des concordancia de las fechas, intenta corregir eso, fuera de eso está todo ok y se basa en el EDT.

**Comment by stroomed** [comment]
Se agrega imagen a gran escala de cronograma.
![gantt](https://user-images.githubusercontent.com/43097139/80926462-72798000-8d65-11ea-8524-d6a1bbcde986.png)

**Comment by stroomed** [comment]
Se agrega detalle de cronograma.

![parte 1](https://user-images.githubusercontent.com/43097139/80926487-a5237880-8d65-11ea-9d45-d619227695c7.png)

![parte 2](https://user-images.githubusercontent.com/43097139/80926507-c1bfb080-8d65-11ea-85da-e420a6d34fe7.png)

![image](https://user-images.githubusercontent.com/43097139/80926520-d9973480-8d65-11ea-99cd-ad2a31e30124.png)

**Comment by stroomed** [comment]
Se da por corregido con el siguiente cronograma:

![image](https://user-images.githubusercontent.com/43097139/81096375-429cba80-8ed4-11ea-9744-774974516d52.png)

Cuyo desglose es:

![image](https://user-images.githubusercontent.com/43097139/81095135-93abaf00-8ed2-11ea-8585-6373cc0d59a9.png)
![image](https://user-images.githubusercontent.com/43097139/81095817-8642f480-8ed3-11ea-9b2c-cb45a4bcace0.png)
![image](https://user-images.githubusercontent.com/43097139/81095864-98249780-8ed3-11ea-94fe-9437a533bcbe.png)
![image](https://user-images.githubusercontent.com/43097139/81095911-ad012b00-8ed3-11ea-8e10-77714764bca1.png)
![image](https://user-images.githubusercontent.com/43097139/81095965-c1452800-8ed3-11ea-8ad1-c5bb946f4633.png)
