### ISSUE TITLE
Subir trazabilidad de requerimientos

### ISSUE THREAD

**Issue by stroomed** [stroomed/tesis2020#14]
- [x] Desarrollar trazabilidad en base a requerimientos entregados por Fabricio.
- [x] Subir trazabilidad para su revisión en grupo.

---

La trazabilidad y sus correspondientes revisiones deberán ser subidas al issue como comentario (no editar issue).

---

- [x] Revisión hecha por Ricardo Gutiérrez
- [x] Revisión hecha por Fabricio Guzmán

**Comment by Gabriel-Barria** [comment]
Matriz   de trazabilidad
--
Nombre del proyecto | Actualiza Street
ID req | Descripción del requerimiento | Fuente del requerimiento | EDT Entregables | Estrategia de testing | Encargado
  |   |   |   |   |  
RF-01 | Toma de información de imágenes: Toda   la informacion que el software principal vaya procesando debera ser   administrada por la API. | Reunion con el cliente | 3.2.1 Desarrollo en Django Rest | Pruebas de caja negra |  
RF-02 | Historial de solicitudes de   información: Todas las solicitudes realizadas al Software principal se iran   almacendando en un historial. | Reunion con el cliente | 3.2.1 Desarrollo en Django Rest | Pruebas   de caja negra |  
RF-03 | Historial asíncrono: En caso de que   una de las solicitudes sea video, la api se limitara solo a mostrar la   informacion necesaria.                                                             Cada vez que se haga una solicitud al software principal utilizando   videos, La api realizara un filtro el cual se encargara de mostrar solo la   informacion necesaria, omitiendo repeticiones e informacion fuera de lugar. | Reunion con el cliente | 3.2.1 Desarrollo en Django Rest | Pruebas   de caja negra y caja blanca |  
RF-04 | Diseño de sistema administrativo: El   diseño de la pagina principal sera de tipo administrador, utilizando como   plantilla el template descrito en el grafico 1.0.                                                                                             La pagina debe contener un historial con la informacion de las   solicitudes realizadas al servidor.     Debe contener un grafico que muestre la cantidad de señales   detectadas, cuantas se encuentran en buen estado y cuantas se encuentran en   mal estado.               Tanto el   historial como los graficos seran visualizados en la pagina principal y   dependiendo de los intereses del usuario estos serian seleccionables para   mostrar mas detalles. | Reunion con el cliente | 2.1   Aaptacion del template | Pruebas   de diseño |  
RF-05 | Control de acceso exclusivo de   administrador: Para poder acceder a todos las funciones del sistema sera   necesario logearse y para ello debe tener un usuario y contraseña validos,   los cuales solo le seran proporcionado a los administradores del sitio. | Reunion con el cliente | 3.2.1 Desarrollo en Django Rest | Pruebas   de caja negra y caja blanca |  
RF-06 | Gráficos en base a la información   recopilada: Los graficos mostraran la informacion sobre la cantidad de   señales detectadas, cantidad en mal estado y cuantas se encuantran en buen   estado.                                Estas seran mostradas en base a lo que requiera el usuario, puede ser   graficos en base a cada minuto, horas, dias, semanas, meses o años. | Reunion con el cliente | 3.2.1 Desarrollo en Django Rest | Pruebas   de caja negra y caja blanca |  
RNF-01 | Base de datos en MongoDB: Toda la   informacion relacionada a la deteccion de las imágenes, sera almacenada en   MongoDB, esto incluye informacion de cantidad de señales detectadas, cantidad   de señales en mal estado y cantidad de señales en buen estado. | Reunion con el cliente | 3.1.1 Base de datos en MongoDB | Pruebas   de caja negra y caja blanca |  
RNF-02 | Api en Django Rest: La API sera creada con el Framework Django Rest. | Reunion con el cliente | 3.2.1 Desarrollo en Django Rest |   |  
RNF-03 | API modular: El API es modular, es independiente al software principal   y solamente una parte del mismo. | Reunion con el cliente |   |   |  
RNF-04 | Base de datos para los usuarios: El sistema contara con una base   diferente para almacenar la informacion relacionada a la interfaz y su   funcionalidades. | Reunion con el cliente | 3.1.2 Base de datos para los usuarios |   |  
RNF-05 | Estándar de calidad: La API debe respetar los siguientes   principios:  Funcionalidad debe   adecuarse a las necesidades del usuario, debe ser precisa en los resultados y   segura. Confiabilidad debe ser tolerante a fallos y contar con   recuperabilidad. Usabilidad debe ser comprensible, aprendible, operable y   atractiva. Eficiencia debe reaccionar a tiempo. Mantenibilidad debe ser   analizable, modificabley estable.Portabilidad debe ser adaptable e   instalable. | Reunion con el cliente | 4.1 Pruebas Generales |   |

**Comment by Gabriel-Barria** [comment]
ID req | Descripción del requerimiento | Fuente del requerimiento | EDT Entregables | Estrategia de testing | Encargado
-- | -- | -- | -- | -- | --
RF-01 | Toma   de información de imágenes: Toda la información que el software principal   vaya procesando deberá ser administrada por la API. | Reunión   con el cliente | 3.2.1   Desarrollo en Django Rest | Pruebas   de caja negra |  Fabricio Guzmán  y Nicol Quintuy.
RF-02 | Historial   de solicitudes de información: Todas las solicitudes realizadas al Software   principal se irán almacenando en un historial. | Reunión   con el cliente | 3.2.1   Desarrollo en Django Rest | Pruebas   de caja negra |  Fabricio Guzmán  y Nicol Quintuy
RF-03 | Historial   asíncrono: En caso de que una de las solicitudes sea video, él API se limitara   solo a mostrar la información necesaria.                                                             Cada vez que se haga una solicitud al software principal utilizando   videos, El api realizara un filtro el cual se encargara de mostrar solo la información   necesaria, omitiendo repeticiones e información fuera de lugar. | Reunión   con el cliente | 3.2.1   Desarrollo en Django Rest | Pruebas   de caja negra y caja blanca | Fabricio Guzmán  y Nicol Quintuy 
RF-04 | Diseño   de sistema administrativo: El diseño de la página principal será de tipo   administrador, utilizando como plantilla el témplate descrito en el grafico   1.0.                                                                                             La página debe contener un historial con la información de las   solicitudes realizadas al servidor.     Debe contener un gráfico que muestre la cantidad de señales   detectadas, cuantas se encuentran en buen estado y cuantas se encuentran en   mal estado.               Tanto el   historial como los gráficos serán visualizados en la página principal y   dependiendo de los intereses del usuario estos serían seleccionables para   mostrar más detalles. | Reunión   con el cliente | 2.1   Adaptacion del template | Pruebas   de diseño | Ricardo Gutiérrez, Gabriel Barría 
RF-05 | Control   de acceso exclusivo de administrador: Para poder acceder a todos las   funciones del sistema serán necesario logearse y para ello debe tener un   usuario y contraseña válidos, los cuales solo le serán proporcionado a los   administradores del sitio. | Reunión   con el cliente | 3.2.1   Desarrollo en Django Rest | Pruebas   de caja negra y caja blanca |  Fabricio Guzmán  y Nicol Quintuy 
RF-06 | Gráficos   en base a la información recopilada: Los gráficos mostraran la información   sobre la cantidad de señales detectadas, cantidad en mal estado y cuantas se encuentran   en buen estado.                                Estas serán mostradas en base a lo que requiera el usuario, puede ser gráficos   en base a cada minuto, horas, días, semanas, meses o años. | Reunión   con el cliente | 3.2.1   Desarrollo en Django Rest | Pruebas   de caja negra y caja blanca |  Fabricio Guzmán  y Nicol Quintuy 
RNF-01 | Base   de datos en MongoDB: Toda la información relacionada a la detección de las imágenes   será almacenada en MongoDB, esto incluye información de cantidad de señales   detectadas, cantidad de señales en mal estado y cantidad de señales en buen   estado. | Reunión   con el cliente | 3.1.1   Base de datos en MongoDB | Pruebas   de caja negra y caja blanca |  Fabricio Guzmán  y Nicol Quintuy 
RNF-02 | Api   en Django Rest: La API será creada con el Framework Django Rest. | Reunión   con el cliente | 3.2.1   Desarrollo en Django Rest |  Pruebas   de caja negra y caja blanca   | Fabricio Guzmán  y Nicol Quintuy 
RNF-03 | API   modular: El API es modular, es independiente al software principal y   solamente una parte de este. | Reunión   con el cliente |  Aprobación del informe final |  Pruebas   de caja negra y caja blanca  | Fabricio Guzmán  y Nicol Quintuy 
RNF-04 | Base   de datos para los usuarios: El sistema contara con una base diferente para   almacenar la información relacionada a la interfaz y su funcionalidad. | Reunión   con el cliente | 3.1.2   Base de datos para los usuarios | Pruebas   de caja negra y caja blanca |  Fabricio Guzmán  y Nicol Quintuy  
RNF-05 | Estándar   de calidad: La API debe respetar los siguientes principios:  Funcionalidad debe adecuarse a las necesidades   del usuario, debe ser precisa en los resultados y segura. Confiabilidad debe   ser tolerante a fallos y contar con recuperabilidad. Usabilidad debe ser   comprensible, aprensible, operable y atractiva. Eficiencia debe reaccionar a   tiempo. Mantenibilidad debe ser analizable, modificable estable. Portabilidad   debe ser adaptable e instalable. | Reunión   con el cliente | 4.1   Pruebas Generales | Pruebas   de caja negra y caja blanca - Pruebas de estres | Ricardo Gutiérrez, Gabriel Barría, Nicol Quintuy, Fabricio Guzmán

**Comment by Aijin-01** [comment]
A grandes rasgos están bien las especificaciones, pero el tema de cerrar el tipo de dato con el que se trabajará es algo peligroso, ya que pueden aparecer nuevos tipos de datos solicitados por el cliente, esta bien que el tomar la información de las señales de transito y su estado sea especificado, pero no el lo único, y eso se da a entender en las especificaciones.
