### ISSUE TITLE
Creación de Mockups

### ISSUE THREAD

**Issue by stroomed** [stroomed/tesis2020#16]
- [x] Diseñar adaptación de template (indicada anteriormente) que tendrá la interfaz de la aplicación.
- [x] Obtener comentarios del cliente respecto de diseño en curso.

---

- [x] Subir mockup para revisión grupal.

**Comment by Gabriel-Barria** [comment]
![login](https://user-images.githubusercontent.com/62030014/81886511-e0deef00-956a-11ea-8f35-6e1cf90d1479.PNG)

![home](https://user-images.githubusercontent.com/62030014/81886519-e50b0c80-956a-11ea-8eac-6416b357faeb.PNG)

![historial](https://user-images.githubusercontent.com/62030014/81886525-e89e9380-956a-11ea-8dbf-c98e928b63dd.PNG)

![Graficos](https://user-images.githubusercontent.com/62030014/81886527-eccab100-956a-11ea-96fa-e131d2ff2e0f.PNG)
