### ISSUE TITLE
Adaptación de interfaz

### ISSUE THREAD

**Issue by stroomed** [stroomed/tesis2020#17]
- [x] Codificar template escogida.
- [x] Adaptar código de template a diseño establecido en mockups.
- [x] Fecha límite: Martes 26 de Mayo.
- [x] Revisión grupal Miércoles 27 de Mayo.

---

- [x] Solicitar revisión de en conjunto con el cliente.

**Comment by Aijin-01** [comment]
Vistas agregadas y redireccionadas a sus respectivos .html

**Comment by Aijin-01** [comment]
Arreglo de vistas en la api y correcta distribución de estas
