### ISSUE TITLE
Realizar diagramas UML

### ISSUE THREAD

**Issue by stroomed** [stroomed/tesis2020#18]
#### Fabricio
- [x] Diagramas de casos de uso.

#### Ricardo
- [x] Diagrama de clases.

---

- [x] Revisión grupal.

---

PD: Recordar solicitar apoyo en caso de ser necesario.

**Comment by Aijin-01** [comment]
![casos de uso](https://user-images.githubusercontent.com/62028929/82166995-4e02c500-9888-11ea-9450-940c8a0c587b.png)

**Comment by stroomed** [comment]
![image](https://user-images.githubusercontent.com/43097139/81877515-4cb55d80-9553-11ea-8b10-77967f72f44a.png)

**Comment by Aijin-01** [comment]
Hay algo que no me calza entre la conexión entre consulta y validación, pero fuera de eso todo está ok. Respecto a mi observación, es un tema de posicionamiento, desde la validación se harán las consultas?...solo se puede hacer un solo tipo de consulta?

**Comment by stroomed** [comment]
eso fue algo que me faltó, lo agrego ahora

**Comment by stroomed** [comment]
Diagrama actualizado

![image](https://user-images.githubusercontent.com/43097139/81884666-71670080-9566-11ea-8ce0-d874b50e74e7.png)

**Comment by stroomed** [comment]
Corrección de diagrama de clases

![image](https://user-images.githubusercontent.com/43097139/82160031-64952600-9860-11ea-9756-245bec7dbdac.png)
