### ISSUE TITLE
Diseño de Base de Datos

### ISSUE THREAD

**Issue by stroomed** [stroomed/tesis2020#19]
#### Base de datos de información de aplicación (MongoDB).
- [x] Diseñar siguiendo requerimientos obtenidos con anterioridad.
- [x] Subir diseño a issue.

#### Base de datos de usuarios (MySql).
- [x] Diseñar siguiendo requerimientos obtenidos con anterioridad.
- [x] Subir diseño a issue.

#### General
- [x] Fecha límite: Martes 26 de Mayo.
- [x] Revisión grupal Miércoles 27 de Mayo.

---

- [x] Solicitar revisión con el cliente.

---

PD: Recordar solicitar apoyo en caso de ser necesario.

**Comment by Gabriel-Barria** [comment]
![Diagrama1](https://user-images.githubusercontent.com/62030014/82773424-fe844200-9e0f-11ea-93b3-0f5919b0654f.png)

**Comment by Gabriel-Barria** [comment]
![mongodb](https://user-images.githubusercontent.com/62030014/82773690-a732a180-9e10-11ea-82f8-5f6739dc1f6e.png)

**Comment by stroomed** [comment]
Creo que la base de datos SQL para los usuarios, podría verse mejor de esta forma:

![image](https://user-images.githubusercontent.com/43097139/82827635-6ae95a80-9e7d-11ea-90e3-44c0ac47f8e5.png)
