### ISSUE TITLE
Corrección y ajustes

### ISSUE THREAD

**Issue by stroomed** [stroomed/tesis2020#24]
- [x] Corregir errores encontrados en prototipo.
- [x] Ajustar diseño a comentarios de cliente en reunión del 11/06.
- [x] Realizar pruebas de comprobación de correcciones.

---

- [x] Fecha límite: Sábado 20 de Junio.
- [x] Revisión grupal Domingo 21 de Junio.

**Comment by Aijin-01** [comment]
Correcciones menores al las vistas
