### ISSUE TITLE
Fase de Pruebas

### ISSUE THREAD

**Issue by stroomed** [stroomed/tesis2020#25]
- [x] Realizar pruebas de diseño.
- [x] Realizar pruebas de estrés.
- [x] Completar pruebas de caja blanca.
- [x] Completar pruebas de caja negra.

---

- [x] Documentar todas las pruebas realizadas a la aplicación.

---

- [x] Fecha límite: Sábado 20 de Junio.
- [x] Revisión grupal Domingo 21 de Junio.

**Comment by Aijin-01** [comment]
[pruebas.docx](https://github.com/stroomed/tesis2020/files/4875770/pruebas.docx)
