### ISSUE TITLE
Definir alcance

### ISSUE THREAD

**Issue by stroomed** [stroomed/tesis2020#7]
- [x] Define objetivos del proyecto.
- [x] Establece límites del proyecto.
- [x] Establece restricciones del proyecto.
- [x] Explica las actividades que le darán vida al proyecto.

---

- [x] Revisión hecha por Fabricio Guzmán
- [x] Revisión hecha por Nicol Quintuy
- [x] Revisión hecha por Gabriel Barría

**Comment by stroomed** [comment]
### Objetivo General

Desarrollar una interfaz web qué, por medio de IA y cámaras de video, se encargará de obtener la información respecto de la ubicación y estado físico de las señales de tránsito. Todo esto tendrá la finalidad de permitir una mayor y mejor precisión en el análisis de las señaléticas, disminuyendo los recursos destinados actualmente a esta tarea.

### Objetivos Específicos

- El sistema deberá recibir la información desde la API, procesarla y mostrarla al usuario que la esté solicitando.
- La interfaz del sistema deberá ser agradable al usuario y, por sobre todo, deberá ser responsive.
- La aplicación deberá tener la capacidad de mantenerse actualizada en tiempo real.

### Alcance del Proyecto

El sistema se desarrollará en base al lenguaje de programación Python y a su framework Django, por lo que los programadores deberán saber este lenguaje y el uso del framework anteriormente mencionado, mientras que el resto del equipo deberán tener nociones básicas de programación.

El funcionamiento de la aplicación web se limitará a la recepción de imágenes (y posiblemente video) desde una API ya existente, interpretar los datos recibidos y entregar la información al usuario que los esté solicitando. Además, la aplicación deberá guardar un registro de los datos procesados y los usuarios que hayan solicitado dicha información.

Adicionalmente, el sistema tendrá un nivel de seguridad tal que, si un usuario no se encuentra registrado y/o con permisos, no podrá ingresar a la aplicación.

Por último, se recalca que el desarrollo que realizará este equipo corresponde al modulo que contiene la interfaz gráfica del sistema, el procesamiento de la información y la muestra al usuario. 

### Actividades de producción

Esta sección es, básicamente, el cómo se llevará a cabo este proyecto, es decir, son todas las actividades que se deben hacer para lograr esta propuesta. Estas actividades son:

- Toma y confirmación de requerimientos.
- Diseñar diagramas necesarios para la comprensión del sistema.
- Diseñar bases de datos, acorde a las necesidades del cliente demostradas en los requerimientos.
- Diseñar interfaz gráfica del prototipo.
- Confirmar junto con el cliente el que se esté avanzando por el camino correcto.
- Creación de prototipo funcional para evaluación del cliente.
- Realizar ajustes al prototipo, acorde a lo que sea indicado por el cliente en su evaluación, siempre y cuando esto sea posible.
- Desarrollar pruebas de distintos tipos, indicadas en el EDT del proyecto (presentado más adelante en este informe).
- Presentar al cliente para visto bueno.
- Corrección final de errores.
- Realizar implementación y entrega de manual de usuario.

**Comment by Gabriel-Barria** [comment]
Se debe aclarar que los objetivos específicos se refieren al módulo que se está creando, y que el objetivo general es del proyecto completo, además, el primer objetivo específico está mal, ya que en ninguna parte con anterioridad se menciona algo del 90%, fueron uno de los comentarios en el informe anterior.
