### ISSUE TITLE
Definir requerimientos

### ISSUE THREAD

**Issue by stroomed** [stroomed/tesis2020#8]
- [x] Se hace la diferencia entre requerimientos funcionales y no funcionales.
- [x] Requerimientos se explican correcta y completamente.
- [x] Los requerimientos permiten entender qué es lo que quiere el cliente.

---

- [x] Revisión hecha por Nicol Quintuy
- [x] Revisión hecha por Gabriel Barría
- [x] Revisión hecha por Ricardo Gutiérrez

**Comment by Aijin-01** [comment]
Código | Requerimiento | Especificación
-- | -- | --
Requerimientos Funcionales
RF-01 | Toma de información   de imágenes | Recibir información   proveniente del módulo principal y administrarla.
RF-02 | Historial de   solicitudes de información | Mostrar un historial   sobre las solicitudes que se han hecho al servidor de la API.
RF-03 | Historial asíncrono | La información mostrada por la API no será en base a la cantidad de frames enviadas al servidor, sino las necesarias, en caso de que la solicitud sea un video.
RF-04 | Diseño de sistema   administrativo | La API debe tener   interfaz administrativa, usando el template ![Ejemplo de template](https://user-images.githubusercontent.com/62028929/80891158-4b04b380-8c90-11ea-8b11-81ff1029f587.png) donde se muestran diferentes datos, que en nuestro caso serían de solicitudes al servidor.
RF-05 | Control de acceso   exclusivo de administrador | Un sistema de inicio   de sesión para el Admin
RF-06 | Gráficos en base a   la información recopilada | Gráficos en base a   la información recopilada.
Requerimientos no funcionales
RNF-01 | Base de datos en   MongoDB para la información | La información de la   detección de imágenes debe ser almacenada en una base de datos no relacional   de MongoDB
RNF-02 | Api en Django Rest | El modulo debe estar   creada en el framework Django Rest
RNF-03 | API modular | La api es un módulo,   una parte de software principal
RNF-04 | Base de datos para   los usuarios | Una base de datos   diferente para el control de Django Rest
RNF-05 | Estándar de calidad | La API debe cumplir con el estándar de calidad 1012-2004 IEEE.

**Comment by Gabriel-Barria** [comment]
Uno de los requerimientos del cliente es la calidad, sería bueno agregarlo. 
Tampoco hay ni un requerimiento que diga que la API permite recibir imágenes y videos, ni que estos son redireccionados al modulo principal para que este haga la detección.
Tengo comentarios en los siguientes requerimientos:
RF-01, Se puede explicar mejor, se entiende que recibe la información y la administra, pero en específico ¿qué hace?, el módulo sirve de intermediario entre usuario y el módulo principal, ósea la imagen es cargada en el api y este la redirecciona al módulo principal el cual se encarga de hacer la detección y devolver los resultados, con esa descripción no se entiende eso.
RF-03, creo que podría redactarse un poco mejor, para ayudar a la comprensión de este.
RF-04, dejar un enlace no creo que sea la mejor opción para explicar el requerimiento, se supone que, en el documento, cada uno de los requerimientos se deben explicar completa y correctamente y por lógica no se debería de salir de este para entenderlo, sería mejor anexar un mockup de la interfaz de administrador y en la descripción referenciar dicho mockup.

**Comment by stroomed** [comment]
1012-2004 IEEE
