### ISSUE TITLE
Definir plan de riesgos

### ISSUE THREAD

**Issue by stroomed** [stroomed/tesis2020#9]
- [x] Define riesgos del proyecto.
- [x] Identifica probabilidad e impacto de cada riesgo.
- [x] Elabora estrategias de defensa ante cada riesgo.
- [x] Elabora plan de respuesta ante cada riesgo.

---

- [x] Revisión hecha por Ricardo Gutiérrez
- [x] Revisión hecha por Gabriel Barría
- [x] Revisión hecha por Fabricio Guzmán

**Comment by nicolquintuy** [comment]
![R](https://user-images.githubusercontent.com/62029314/80930289-ab731e00-8d80-11ea-840b-0c97a5f5fb44.PNG)

![evaluacion](https://user-images.githubusercontent.com/62029314/80930290-ae6e0e80-8d80-11ea-9747-6d5c42ff100e.PNG)

![plan](https://user-images.githubusercontent.com/62029314/80930299-baf26700-8d80-11ea-875e-91d5257f8f2e.PNG)
